### ISSUE TITLE
Cabinet-compatible LZX compression mode?

### ISSUE THREAD

**Issue by elasota** [ebiggers/wimlib#10]
I'm thinking of doing a PR for this but I am wondering if it is out-of-scope for this project.

Some context: Right now as best I can tell, there are basically two options for making CAB files on non-Windows platforms: gcab and WINE's implementation of cabinet.dll.  Both only support deflate compression.  It would be nice to add support for those by using the compression functions exposed by wimlib, but it appears the E8 filter behavior is incompatible (it can't be disabled, and when enabled, it is active past the 32768th chunk, which differs from the cabinet behavior).

WIM doesn't need this at all though, so I'm wondering if adding a cabinet-compatible mode to the LZX compressor would be appropriate for this project.

**Comment by ebiggers** [comment]
I think this is out of scope for the project, especially considering that proper support for LZX in cabinet files would also require streaming.  But please feel free to reuse wimlib's open source code (in line with its license).
