### ISSUE TITLE
Installation documentation is wrong

### ISSUE THREAD

**Issue by danielmain** [ebiggers/wimlib#3]
`configure` does not exist in the repository while the README.md says you have to run `./configure && make && sudo make install`

![CleanShot 2024-01-17 at 09 17 52@2x](https://github.com/ebiggers/wimlib/assets/4303099/130a5af1-f972-41dc-9e81-1a9629594b34)

**Comment by ebiggers** [comment]
Well, it's not wrong per se, it's just assumed that you're building from a distribution tarball.  I'll clarify the directions.

**Comment by ebiggers** [comment]
I've improved the documentation.
