### ISSUE TITLE
[demand] tutorial for add msu and exe update package

### ISSUE THREAD

**Issue by amidevous** [ebiggers/wimlib#9]
please put a tutorial to explain how to add updates in msu and one in an install.wim file

for dism

please put a tutorial to explain how to add updates in msu and one in an install.wim file

for dism

it would be necessary to do the same thing with winlib because there with the information on your site

```
Md c:\mount
Dism /Get-ImageInfo /imagefile:"C:\Users\%USERNAME%\Downloads\Windowsextractiso\sources\install.wim"
dism /mount-image /imagefile:"C:\Users\%USERNAME%\Downloads\Windowsextractiso\sources\install.wim" /index:1 /mountdir:c:\Mount
Dism /Image:C:\mount /Add-Package /PackagePath:"C:\Users\%USERNAME%\Downloads\windows10.0-kb4016635-x64_2b1b48aa6ec51c019187f15059b768b1638a21ab.msu"
dism /unmount-image /mountdir:c:\mount /commit
```

for wimlib (require install package wimlib and wimlib-utils)

```
mkdir $HOME/mount
# for wimlib alternative # Dism /Get-ImageInfo /imagefile:"$HOME/Windowsextractiso/sources/install.wim"
sudo wiminfo $HOME/Windowsextractiso/sources/install.wim
# for wimlib alternative # dism /mount-image /imagefile:"C:\Users\%USERNAME%\Downloads\Windowsextractiso\sources\install.wim" /index:1 /mountdir:c:\Mount
wimmount $HOME/Windowsextractiso/sources/install.wim 1 $HOME/mount
# for wimlib alternative # Dism /Image:$HOME/mount /Add-Package /PackagePath:"$HOME/Downloads/windows10.0-kb4016635-x64_2b1b48aa6ec51c019187f15059b768b1638a21ab.msu"
wim??????????????
# for wimlib alternative # dism /unmount-image /mountdir:$HOME/mount /commit
wimapply $HOME/Windowsextractiso/sources/install.wim 1 $HOME/mount

```

in other words please indicate how to do this in wimlib

```
# for wimlib alternative # Dism /Image:$HOME/mount /Add-Package /PackagePath:"$HOME/Downloads/windows10.0-kb4016635-x64_2b1b48aa6ec51c019187f15059b768b1638a21ab.msu"
wim??????????????
```

this function and the most important of all dism functions

which we need to use in wimlib

without this option wimlib has no practical interest

because the main purpose of editing wim images

this is precisely to integrate the updates

because extracting and creating .wim files can already be done with 7zip and p7zip

in this option is the most important

without it the wimlib program has no interest

**Comment by ebiggers** [comment]
wimlib focuses on the lower-level support for WIM files.  I don't plan to look into adding an equivalent to `/Add-Package`, but if anyone is able to figure out how to do this (i.e. what file edit operations are involved) I would be glad to consider a contribution.
